# Generated by Django 4.1.2 on 2023-07-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFunko', '0002_remove_categoria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='funko',
            name='detalle',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
